/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itm_callitm_ITMWrapper */

#ifndef _Included_com_itm_callitm_ITMWrapper
#define _Included_com_itm_callitm_ITMWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itm_callitm_ITMWrapper
 * Method:    ITM_P2P_TLS_Ex
 * Signature: (DD[DIDDIDDIDDD[D[JLcom/itm/callitm/ITMWrapper/IntermediateValues;)I
 */
JNIEXPORT jint JNICALL Java_com_itm_callitm_ITMWrapper_ITM_1P2P_1TLS_1Ex
  (JNIEnv *, jobject, jdouble, jdouble, jdoubleArray, jint, jdouble, jdouble, jint, jdouble, jdouble, jint, jdouble, jdouble, jdouble, jdoubleArray, jlongArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
